### ISSUE TITLE
[GHC-9.0.x] Overall compatibility status

### ISSUE THREAD

**Issue by mark-stopka** [2nd-Layer/cardano-core-integration-testing#12]
### Hackage Dependencies

- [x] [ghc-fmt won't build with ghc-9.0.0](https://github.com/2nd-Layer/cardano-core-integration-testing/issues/15) (out-of-tree patch, pending upstream https://github.com/cdornan/fmt/pull/34)

### Cardano Node Components
- [ ] [ghc-typed-protocols won't build with ghc-9.0.0](https://github.com/2nd-Layer/cardano-core-integration-testing/issues/10)
- [ ] [ghc-Win32-network won't build with ghc-9.0.0](https://github.com/2nd-Layer/cardano-core-integration-testing/issues/11)

### Cardano RTView Components
